services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./frontend:/app/frontend
    environment:
      - PYTHONPATH=/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  data:
  frontend:

networks:
  app-network:
    driver: bridge 